### ISSUE TITLE
demo.py error message ' no module named torch._tensor'

### ISSUE THREAD

**Issue by songhc8** [google-research/omniglue#31]
thanks for sharing your work. 

How to fix this error. 

`(base) root@song-HP-Z1-Entry-Tower-G6:/song/work/tmp/cpp_tmp/vision/deep_learning/omniglue# python demo.py /song/work/tmp/python_tmp/reconstruction/data/real/20240923/images/mono_113026.png /song/work/tmp/python_tmp/reconstruction/data/real/20240923/images/mono_113053.png 
2024-09-23 07:51:33.056630: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-23 07:51:33.597991: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> Loading images...
> Loading OmniGlue (and its submodules: SuperPoint & DINOv2)...
2024-09-23 07:51:34.552852: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-09-23 07:51:34.553174: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
WARNING:tensorflow:From /song/work/tmp/cpp_tmp/vision/deep_learning/omniglue/src/omniglue/superpoint_extract.py:40: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.saved_model.load` instead.
2024-09-23 07:51:46.244197: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
Traceback (most recent call last):
  File "demo.py", line 95, in <module>
    main(sys.argv)
  File "demo.py", line 46, in main
    og = omniglue.OmniGlue(
  File "/song/work/tmp/cpp_tmp/vision/deep_learning/omniglue/src/omniglue/omniglue_extract.py", line 42, in __init__
    self.dino_extract = dino_extract.DINOExtract(dino_export, feature_layer=1)
  File "/song/work/tmp/cpp_tmp/vision/deep_learning/omniglue/src/omniglue/dino_extract.py", line 32, in __init__
    state_dict_raw = torch.load(cpt_path, map_location='cpu')
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.8/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'torch._tensor'`

**Comment by songhc8** [comment]
bug can be fixed by installing python 3.10 first,  and then intalling this repo.
